package com.ies.mapper;

import com.ies.domain.Breakage;
import com.ies.domain.BreakageCriteria;

import java.math.BigDecimal;
import java.util.List;

import com.ies.vo.BreakageVo;
import com.ies.vo.statistics.BreakageReportVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BreakageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int countByExample(BreakageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByExample(BreakageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insert(Breakage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insertSelective(Breakage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Breakage> selectByExampleWithRowbounds(BreakageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Breakage> selectByExample(BreakageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    Breakage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Breakage record, @Param("example") BreakageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExample(@Param("record") Breakage record, @Param("example") BreakageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKeySelective(Breakage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakage
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKey(Breakage record);

    List<Breakage> loadAllBreakage(BreakageVo breakageVo);

    List<BreakageReportVo> breakageReport(BreakageReportVo breakageReportVo);

    BigDecimal breakageTotalPriceReport(BreakageReportVo breakageReportVo);
}