package com.ies.mapper;

import com.ies.domain.Caigou;
import com.ies.domain.CaigouCriteria;
import java.util.List;

import com.ies.vo.CaigouVo;
import com.ies.vo.statistics.CaigouReportVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CaigouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int countByExample(CaigouCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByExample(CaigouCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insert(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insertSelective(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Caigou> selectByExampleWithRowbounds(CaigouCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Caigou> selectByExample(CaigouCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    Caigou selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Caigou record, @Param("example") CaigouCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExample(@Param("record") Caigou record, @Param("example") CaigouCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKeySelective(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKey(Caigou record);

    List<Caigou> loadAllCaigou(CaigouVo caigouVo);

    List<CaigouReportVo> caigouReport(CaigouReportVo caigouReportVo);
}