package com.ies.mapper;

import com.ies.domain.Income;
import com.ies.domain.IncomeCriteria;

import java.math.BigDecimal;
import java.util.List;

import com.ies.vo.statistics.IncomeReportVo;
import com.ies.vo.statistics.StockReportVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int countByExample(IncomeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByExample(IncomeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insert(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insertSelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Income> selectByExampleWithRowbounds(IncomeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Income> selectByExample(IncomeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    Income selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Income record, @Param("example") IncomeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExample(@Param("record") Income record, @Param("example") IncomeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKeySelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKey(Income record);

    List<IncomeReportVo> incomeReport(IncomeReportVo incomeReportVo);

    BigDecimal incomeTotalPriceReport(IncomeReportVo incomeReportVo);
}