package com.ies.mapper;

import com.ies.domain.Item;
import com.ies.domain.ItemCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int countByExample(ItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int deleteByExample(ItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    List<Item> selectByExampleWithRowbounds(ItemCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    List<Item> selectByExample(ItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    Item selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int updateByExample(@Param("record") Item record, @Param("example") ItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    int updateByPrimaryKey(Item record);
}