package com.ies.mapper;

import com.ies.domain.Sale;
import com.ies.domain.SaleCriteria;

import java.math.BigDecimal;
import java.util.List;

import com.ies.vo.SaleVo;
import com.ies.vo.statistics.SaleReportVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int countByExample(SaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int deleteByExample(SaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int insertSelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    List<Sale> selectByExampleWithRowbounds(SaleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    List<Sale> selectByExample(SaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    Sale selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sale record, @Param("example") SaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int updateByExample(@Param("record") Sale record, @Param("example") SaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int updateByPrimaryKeySelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    int updateByPrimaryKey(Sale record);

    List<Sale> loadAllSale(SaleVo saleVo);

    List<SaleReportVo> saleReport(SaleReportVo saleReportVo);

    BigDecimal saleTotalPriceReport(SaleReportVo saleReportVo);
}