package com.ies.mapper;

import com.ies.domain.StockInOutRecord;
import com.ies.domain.StockInOutRecordCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StockInOutRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int countByExample(StockInOutRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int deleteByExample(StockInOutRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int insert(StockInOutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int insertSelective(StockInOutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    List<StockInOutRecord> selectByExampleWithRowbounds(StockInOutRecordCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    List<StockInOutRecord> selectByExample(StockInOutRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    StockInOutRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockInOutRecord record, @Param("example") StockInOutRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int updateByExample(@Param("record") StockInOutRecord record, @Param("example") StockInOutRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int updateByPrimaryKeySelective(StockInOutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    int updateByPrimaryKey(StockInOutRecord record);
}