package com.ies.mapper;

import com.ies.domain.Supplier;
import com.ies.domain.SupplierCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int countByExample(SupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByExample(SupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Supplier> selectByExampleWithRowbounds(SupplierCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    List<Supplier> selectByExample(SupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    Supplier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Supplier record, @Param("example") SupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByExample(@Param("record") Supplier record, @Param("example") SupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    int updateByPrimaryKey(Supplier record);
}