package com.ies.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Caigou implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.item_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.price
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.count
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caigou.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.id
     *
     * @return the value of caigou.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.id
     *
     * @param id the value for caigou.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.item_id
     *
     * @return the value of caigou.item_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.item_id
     *
     * @param itemId the value for caigou.item_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.price
     *
     * @return the value of caigou.price
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.price
     *
     * @param price the value for caigou.price
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.count
     *
     * @return the value of caigou.count
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.count
     *
     * @param count the value for caigou.count
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.created
     *
     * @return the value of caigou.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.created
     *
     * @param created the value for caigou.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.type
     *
     * @return the value of caigou.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.type
     *
     * @param type the value for caigou.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caigou.user_id
     *
     * @return the value of caigou.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caigou.user_id
     *
     * @param userId the value for caigou.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", price=").append(price);
        sb.append(", count=").append(count);
        sb.append(", created=").append(created);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}