package com.ies.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Income implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.rel_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Long relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.money_in
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private BigDecimal moneyIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.money_out
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private BigDecimal moneyOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.source
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.remark
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.id
     *
     * @return the value of income.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.id
     *
     * @param id the value for income.id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.type
     *
     * @return the value of income.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.type
     *
     * @param type the value for income.type
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.user_id
     *
     * @return the value of income.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.user_id
     *
     * @param userId the value for income.user_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.rel_id
     *
     * @return the value of income.rel_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.rel_id
     *
     * @param relId the value for income.rel_id
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.money_in
     *
     * @return the value of income.money_in
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public BigDecimal getMoneyIn() {
        return moneyIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.money_in
     *
     * @param moneyIn the value for income.money_in
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setMoneyIn(BigDecimal moneyIn) {
        this.moneyIn = moneyIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.money_out
     *
     * @return the value of income.money_out
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public BigDecimal getMoneyOut() {
        return moneyOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.money_out
     *
     * @param moneyOut the value for income.money_out
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setMoneyOut(BigDecimal moneyOut) {
        this.moneyOut = moneyOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.source
     *
     * @return the value of income.source
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.source
     *
     * @param source the value for income.source
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.remark
     *
     * @return the value of income.remark
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.remark
     *
     * @param remark the value for income.remark
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.created
     *
     * @return the value of income.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.created
     *
     * @param created the value for income.created
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbggenerated Sat May 02 11:25:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", relId=").append(relId);
        sb.append(", moneyIn=").append(moneyIn);
        sb.append(", moneyOut=").append(moneyOut);
        sb.append(", source=").append(source);
        sb.append(", remark=").append(remark);
        sb.append(", created=").append(created);
        sb.append("]");
        return sb.toString();
    }
}