package com.ies.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Item implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.code
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unit
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.properties
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private String properties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.supplier
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private Long supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.stock
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.code
     *
     * @return the value of item.code
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.code
     *
     * @param code the value for item.code
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unit
     *
     * @return the value of item.unit
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unit
     *
     * @param unit the value for item.unit
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.properties
     *
     * @return the value of item.properties
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.properties
     *
     * @param properties the value for item.properties
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.supplier
     *
     * @return the value of item.supplier
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public Long getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.supplier
     *
     * @param supplier the value for item.supplier
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setSupplier(Long supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.stock
     *
     * @return the value of item.stock
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.stock
     *
     * @param stock the value for item.stock
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue May 05 23:07:46 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", unit=").append(unit);
        sb.append(", properties=").append(properties);
        sb.append(", supplier=").append(supplier);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append("]");
        return sb.toString();
    }
}