package com.ies.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Sale implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.item_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.customer_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.price
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.count
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.user_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.created
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.type
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.remark
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.id
     *
     * @return the value of sale.id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.id
     *
     * @param id the value for sale.id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.item_id
     *
     * @return the value of sale.item_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.item_id
     *
     * @param itemId the value for sale.item_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.customer_id
     *
     * @return the value of sale.customer_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.customer_id
     *
     * @param customerId the value for sale.customer_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.price
     *
     * @return the value of sale.price
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.price
     *
     * @param price the value for sale.price
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.count
     *
     * @return the value of sale.count
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.count
     *
     * @param count the value for sale.count
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.user_id
     *
     * @return the value of sale.user_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.user_id
     *
     * @param userId the value for sale.user_id
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.created
     *
     * @return the value of sale.created
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.created
     *
     * @param created the value for sale.created
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.type
     *
     * @return the value of sale.type
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.type
     *
     * @param type the value for sale.type
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.remark
     *
     * @return the value of sale.remark
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.remark
     *
     * @param remark the value for sale.remark
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated Thu May 07 01:59:54 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", customerId=").append(customerId);
        sb.append(", price=").append(price);
        sb.append(", count=").append(count);
        sb.append(", userId=").append(userId);
        sb.append(", created=").append(created);
        sb.append(", type=").append(type);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}