package com.ies.domain;

import java.io.Serializable;
import java.util.Date;

public class Stock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.item_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.status
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.created
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.rel_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Long relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.indexs
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private Integer indexs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.item_id
     *
     * @return the value of stock.item_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.item_id
     *
     * @param itemId the value for stock.item_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.status
     *
     * @return the value of stock.status
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.status
     *
     * @param status the value for stock.status
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.created
     *
     * @return the value of stock.created
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.created
     *
     * @param created the value for stock.created
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.rel_id
     *
     * @return the value of stock.rel_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.rel_id
     *
     * @param relId the value for stock.rel_id
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.indexs
     *
     * @return the value of stock.indexs
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public Integer getIndexs() {
        return indexs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.indexs
     *
     * @param indexs the value for stock.indexs
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    public void setIndexs(Integer indexs) {
        this.indexs = indexs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed May 06 21:23:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", status=").append(status);
        sb.append(", created=").append(created);
        sb.append(", relId=").append(relId);
        sb.append(", indexs=").append(indexs);
        sb.append("]");
        return sb.toString();
    }
}