package com.ies.domain;

import java.io.Serializable;
import java.util.Date;

public class StockInOutRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.item_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.type
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.count
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.rel_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Long relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.created
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.user_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in_out_record.remain
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private Integer remain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.id
     *
     * @return the value of stock_in_out_record.id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.id
     *
     * @param id the value for stock_in_out_record.id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.item_id
     *
     * @return the value of stock_in_out_record.item_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.item_id
     *
     * @param itemId the value for stock_in_out_record.item_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.type
     *
     * @return the value of stock_in_out_record.type
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.type
     *
     * @param type the value for stock_in_out_record.type
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.count
     *
     * @return the value of stock_in_out_record.count
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.count
     *
     * @param count the value for stock_in_out_record.count
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.rel_id
     *
     * @return the value of stock_in_out_record.rel_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.rel_id
     *
     * @param relId the value for stock_in_out_record.rel_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.created
     *
     * @return the value of stock_in_out_record.created
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.created
     *
     * @param created the value for stock_in_out_record.created
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.user_id
     *
     * @return the value of stock_in_out_record.user_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.user_id
     *
     * @param userId the value for stock_in_out_record.user_id
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in_out_record.remain
     *
     * @return the value of stock_in_out_record.remain
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in_out_record.remain
     *
     * @param remain the value for stock_in_out_record.remain
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in_out_record
     *
     * @mbggenerated Wed May 06 21:23:23 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", type=").append(type);
        sb.append(", count=").append(count);
        sb.append(", relId=").append(relId);
        sb.append(", created=").append(created);
        sb.append(", userId=").append(userId);
        sb.append(", remain=").append(remain);
        sb.append("]");
        return sb.toString();
    }
}